# Generated by Django 5.1.3 on 2024-11-13 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyberpong', '0002_rename_user_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='_firstName',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='_lastName',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='_userName',
            new_name='username',
        ),
    ]
